# Generated by Django 3.1.7 on 2021-04-14 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=13)),
                ('start_price', models.IntegerField()),
                ('nomimal_price', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 1, 1, 0, 0, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='LotsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegSubsForLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auction.lots')),
                ('subs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auction.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='lots',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auction.lotsstatus'),
        ),
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('subs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auction.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lot_id', to='auction.subscriber')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auction.betstatus')),
                ('subs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subs_id', to='auction.subscriber')),
            ],
        ),
    ]
