# Generated by Django 3.1.7 on 2021-04-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20210414_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bets',
            options={'verbose_name': 'Bet'},
        ),
    ]
